# Generated by Django 6.0.6 on 2026-07-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedCard',
        ),
    ]
