# Generated by Django 6.0.6 on 2026-07-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_saved_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_engine_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
