# Generated by Django 6.0.6 on 2026-06-25 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], max_length=10)),
                ('custom_interval_days', models.IntegerField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10)),
                ('receiver_account_number', models.CharField(max_length=20)),
                ('receiver_bank_code', models.CharField(max_length=10)),
                ('receiver_account_name', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_link_token', models.CharField(max_length=64, unique=True)),
                ('payment_link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('engine_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('billing_count', models.IntegerField(default=0)),
                ('max_billing_cycles', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('payer_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer_plans', to='core.savedcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.CharField(choices=[('CREATOR', 'Creator'), ('PAYER', 'Payer')], max_length=10)),
                ('creator_code', models.CharField(max_length=6)),
                ('payer_code', models.CharField(max_length=6)),
                ('creator_confirmed', models.BooleanField(default=False)),
                ('payer_confirmed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='plans.payplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
