# Generated by Django 6.0.6 on 2026-07-04 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_update_plan_model_for_engine_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payplan',
            old_name='engine_subscription_id',
            new_name='subscription_engine_id',
        ),
        migrations.CreateModel(
            name='PayPlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PLAN_CREATED', 'Plan Created'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated')], max_length=50)),
                ('previous_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=40, null=True)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=40)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='plans.payplan')),
            ],
        ),
    ]
