# Generated by Django 6.0.6 on 2026-07-04 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_engine_subscription_id_payplan_subscription_engine_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payplan',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payplan',
            name='plan_type',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='payplan',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
