# Generated by Django 6.0.6 on 2026-07-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_payplan_creator_alter_payplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplan',
            name='order_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
