# Generated by Django 6.0.6 on 2026-07-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_payplan_order_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payplan',
            name='subscription_engine_id',
        ),
        migrations.AddField(
            model_name='payplan',
            name='engine_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
