# Generated by Django 6.0.6 on 2026-07-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_payplan_subscription_engine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplan',
            name='cohort_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
