# Generated by Django 6.0.6 on 2026-07-04 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_engine_subscription_id_payplan_subscription_engine_id_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRANSACTION_CREATED', 'Transaction Created'), ('CHARGE_INITIATED', 'Charge Initiated'), ('CHARGE_SUCCEEDED', 'Charge Succeeded'), ('CHARGE_FAILED', 'Charge Failed'), ('PAYOUT_INITIATED', 'Payout Initiated'), ('PAYOUT_SUCCEEDED', 'Payout Succeeded'), ('PAYOUT_FAILED', 'Payout Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed')], max_length=50)),
                ('previous_status', models.CharField(blank=True, choices=[('CHARGE_PENDING', 'Charge Pending'), ('CHARGE_SUCCESS', 'Charge Success'), ('CHARGE_FAILED', 'Charge Failed'), ('PAYOUT_PENDING', 'Payout Pending'), ('PAYOUT_SUCCESS', 'Payout Success'), ('PAYOUT_FAILED', 'Payout Failed'), ('REFUNDED', 'Refunded')], max_length=40, null=True)),
                ('new_status', models.CharField(choices=[('CHARGE_PENDING', 'Charge Pending'), ('CHARGE_SUCCESS', 'Charge Success'), ('CHARGE_FAILED', 'Charge Failed'), ('PAYOUT_PENDING', 'Payout Pending'), ('PAYOUT_SUCCESS', 'Payout Success'), ('PAYOUT_FAILED', 'Payout Failed'), ('REFUNDED', 'Refunded')], max_length=40)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_status',
            field=models.CharField(blank=True, choices=[('CHARGE_PENDING', 'Charge Pending'), ('CHARGE_SUCCESS', 'Charge Success'), ('CHARGE_FAILED', 'Charge Failed'), ('PAYOUT_PENDING', 'Payout Pending'), ('PAYOUT_SUCCESS', 'Payout Success'), ('PAYOUT_FAILED', 'Payout Failed'), ('REFUNDED', 'Refunded')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CHARGE_PENDING', 'Charge Pending'), ('CHARGE_SUCCESS', 'Charge Success'), ('CHARGE_FAILED', 'Charge Failed'), ('PAYOUT_PENDING', 'Payout Pending'), ('PAYOUT_SUCCESS', 'Payout Success'), ('PAYOUT_FAILED', 'Payout Failed'), ('REFUNDED', 'Refunded')], default='CHARGE_PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('plan', 'billing_cycle_number', 'nomba_reference'), name='unique_transaction_per_plan_cycle'),
        ),
        migrations.AddField(
            model_name='transactionevent',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transactions.transaction'),
        ),
    ]
