# Generated by Django 6.0.6 on 2026-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_payplan_creator_alter_payplan_plan_type_and_more'),
        ('transactions', '0002_transactionevent_transaction_payout_failure_reason_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction_per_plan_cycle',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='nomba_reference',
            new_name='charge_reference',
        ),
        migrations.AddField(
            model_name='dunningattempt',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='max_payout_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dunningattempt',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('plan', 'billing_cycle_number', 'charge_reference'), name='unique_transaction_per_plan_cycle'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payout_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payout_status',
        ),
    ]
