# Generated by Django 6.0.6 on 2026-07-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_unique_transaction_per_plan_cycle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DunningAttempt',
        ),
    ]
