# Generated by Django 6.0.6 on 2026-07-07 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0007_payplan_cohort_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], max_length=10)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('proration_mode', models.CharField(choices=[('next_cycle', 'Next Cycle'), ('pro-rated', 'Pro-rated'), ('full_cycle', 'Full Cycle')], default='pro-rated', max_length=20)),
                ('visibility', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='closed', max_length=10)),
                ('receiver_account_name', models.CharField(max_length=255)),
                ('receiver_account_number', models.CharField(max_length=20)),
                ('receiver_bank_code', models.CharField(max_length=10)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to=settings.AUTH_USER_MODEL)),
                ('saved_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='cohorts.savedbankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='invited', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cohorts.cohort')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_membership', to='plans.payplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cohort', 'plan'), name='unique_cohort_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedbankaccount',
            constraint=models.UniqueConstraint(fields=('user', 'account_number', 'bank_code'), name='unique_saved_bank_account'),
        ),
    ]
